# Generated by Django 2.1.5 on 2020-06-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('ID', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=25)),
                ('Contact', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Information',
            },
        ),
    ]
